#!/bin/sh

#   
#   Este script puede ser invocado con uno a tres parámetros:
#   $1  Archivo con el texto del registro (commit message):
#   $2  Fuente del texto del registro:
#       - message: usados los parámetros -m o -F
#       - template: empleado parámetro -t o opción "commit.template"
#       - merge: si es una operación de mezclado o el archivo .git/MERGE_MSG
#                existe
#       - squash: si existe un archivo .git/SQUASH_MSG
#       - commit: en otro caso
#

#   Taking parameters
COMMIT_MSG=$1
MSG_SOURCE=$2
OTHER=$3

#   External scripts 
FILTER_GIT_COMMIT=$(which custom-git-commit-msg)

#   Auxiliary files 
TEMPFILE=$(mktemp)

case "$MSG_SOURCE" in
commit)
    $FILTER_GIT_COMMIT < $COMMIT_MSG > $TEMPFILE
    if [ $? -eq 0 ]; then 
        mv $TEMPFILE $COMMIT_MSG
    else
        exit 1
    fi   
    ;;
esac

exit 0
